openapi: 3.0.0
info:
  title: CBS-SIMULATOR-NODEJS
  version: 1.0.0
servers:
  - url: http://localhost:3000
  - url: https://va-ms-4.prodak.id
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /auth:
    post:
      tags:
        - General
      summary: Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: client
                password: rahasia
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /cifinfoinquiry:
    post:
      tags:
        - General
      summary: CIF Info Inquiry
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                transDateTime: '220715075932'
                bankId: '20'
                cif: '0000007348'
                stan: '010595'
                rrn: '010480000001'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /accountinquiry:
    post:
      tags:
        - General
      summary: Account Inquiry
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                transDateTime: '220715075932'
                bankId: '20'
                cif: '0000007348'
                stan: '010595'
                rrn: '010480000001'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /fundtransfer:
    post:
      tags:
        - General
      summary: Fund Transfer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                transDateTime: '220715075932'
                fromAccount: '801111000122'
                nominal: '10000'
                nomorVA: '00005'
                keterangan: pembayaran
                stan: '010595'
                rrn: '010480000001'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
