openapi: 3.0.0
info:
  title: PRESENCE-API
  version: 1.0.0
servers:
  - url: https://presence-api.srv.co.id/
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: AUTH
  - name: OFFICE CONFIG
  - name: ABSENCE TYPE
  - name: USER
  - name: UPLOAD
  - name: ABSENCE
  - name: OVERTIME
  - name: PRESENCE
  - name: REPORT
paths:
  /api/v1/auth:
    post:
      tags:
        - AUTH
      summary: AUTH
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: kinfjr
                password: rahasia
                device_unique: '381153570610993'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/desktop_auth:
    post:
      tags:
        - AUTH
      summary: DESKTOP AUTH
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: wow123
                password: rahasia
                device_uid: x213
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/forgot_password:
    post:
      tags:
        - AUTH
      summary: FORGOT PASSWORD
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: kurosaki.ari.kun@gmail.com
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/verify_otp:
    post:
      tags:
        - AUTH
      summary: VERIFY OTP
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: kurosaki.ari.kun@gmail.com
                otp: '621477'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/change_password:
    post:
      tags:
        - AUTH
      summary: CHANGE PASSWORD
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: '3'
                password: rahasia
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/office_config:
    get:
      tags:
        - OFFICE CONFIG
      summary: GET
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/office_config/update/{id}:
    post:
      tags:
        - OFFICE CONFIG
      summary: UPDATE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: PT. Digital Amore Kriyanesia
                theme: default
                logo: images/default-logo.png
                latitude: -7.0031342
                longitude: 110.59322727
                radius: 50
                cut_off_date: 25
                amount_of_annual_leave: 12
                work_schedule: 08:00 - 17:00
                updated_by: '1'
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence_type:
    get:
      tags:
        - ABSENCE TYPE
      summary: LIST
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - ABSENCE TYPE
      summary: CREATE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: sakit
                cut_annual_leave: false
                created_by: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence_type/all:
    get:
      tags:
        - ABSENCE TYPE
      summary: ALL
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence_type/{id}:
    get:
      tags:
        - ABSENCE TYPE
      summary: FIND BY ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - ABSENCE TYPE
      summary: UPDATE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: cuti tahunan (edit2)
                cut_annual_leave: true
                updated_by: 1
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - ABSENCE TYPE
      summary: DELETE
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence_type/soft/{id}:
    delete:
      tags:
        - ABSENCE TYPE
      summary: SOFT DELETE
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence_type/restore/{id}:
    post:
      tags:
        - ABSENCE TYPE
      summary: RESTORE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                deleted_by: '1'
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/user:
    get:
      tags:
        - USER
      summary: LIST
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: deleted
          in: query
          schema:
            type: boolean
          example: 'false'
        - name: order
          in: query
          schema:
            type: string
          example: createdAt:desc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - USER
      summary: CREATE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: sodikin
                password: rahasia
                password_confirmation: rahasia
                token: '-'
                email: sodikin@gmail.com
                account_type: karyawan
                name: Sodikin Nur Holis
                address: Kp.Rancamanyar
                description: Lead Dev
                started_work_at: '2018-08-10'
                profile_picture: ''
                device_tracker: true
                can_wfh: true
                phone_number: '62836293911'
                created_by: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/user/{id}:
    get:
      tags:
        - USER
      summary: FIND BY ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - USER
      summary: UPDATE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: ari
                email: kurosaki.ari.kun@gmail.com
                account_type: karyawan
                name: Ari Ardiansyah
                address: Jl. Rancakasiat
                phone_number: '6283822658411'
                description: Fullstack Programmer
                started_work_at: '2018-12-07T00:00:00.000Z'
                profile_picture: images/default.png
                device_tracker: true
                can_wfh: true
                updated_by: 1
                password: rahasia
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - USER
      summary: DELETE
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/user/change_password/{id}:
    put:
      tags:
        - USER
      summary: CHANGE PASSWORD
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                old_password: admin
                new_password: rahasia123
                new_password_confirmation: rahasia123
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/user/soft/{id}:
    delete:
      tags:
        - USER
      summary: SOFT DELETE
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '11'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/user/restore/{id}:
    post:
      tags:
        - USER
      summary: RESTORE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                deleted_by: '1'
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '11'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/user/reset_device_unique:
    post:
      tags:
        - USER
      summary: RESET DEVICE UNIQUE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: '3'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/user/reset_device_uid:
    post:
      tags:
        - USER
      summary: RESET DEVICE UID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: '3'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/user/dashboard1:
    post:
      tags:
        - USER
      summary: DASHBOARD 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                date: '2023-04-25'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/user/today_check:
    post:
      tags:
        - USER
      summary: TODAY CHECK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                date: '2023-06-10 00:00:00'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/user/list/monitor_karyawan:
    get:
      tags:
        - USER
      summary: LIST MONITORING KARYAWAN
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: date
          in: query
          schema:
            type: string
          example: '2023-06-13'
        - name: ''
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/user/list/jatah_cuti_tahunan:
    get:
      tags:
        - USER
      summary: LIST JATAH CUTI TAHUNAN
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: query
          schema:
            type: integer
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/upload/image:
    post:
      tags:
        - UPLOAD
      summary: IMAGE
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/upload/document:
    post:
      tags:
        - UPLOAD
      summary: ATTACHMENT
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                document:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence:
    get:
      tags:
        - ABSENCE
      summary: LIST
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence/{id}:
    get:
      tags:
        - ABSENCE
      summary: DETAIL
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence/submission/{absence_id}:
    get:
      tags:
        - ABSENCE
      summary: LIST SUBMISSION
      security:
        - bearerAuth: []
      parameters:
        - name: absence_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence/list/submission:
    get:
      tags:
        - ABSENCE
      summary: LIST SUBMISSION - ADMIN
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: start_date
          in: query
          schema:
            type: string
          example: '2023-05-13 00:00:00'
        - name: end_date
          in: query
          schema:
            type: string
          example: '2023-05-13 23:59:59'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence/submission:
    post:
      tags:
        - ABSENCE
      summary: SUBMISSION
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 3
                absence_at: '2023-03-14'
                absence_type_id: 1
                desc: Sakit karena kemarin kehujanan
                attachment: ''
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence/approve:
    post:
      tags:
        - ABSENCE
      summary: APPROVE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                submission_id: 2
                authorization_by: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence/cancel:
    post:
      tags:
        - ABSENCE
      summary: CANCEL
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                absence_id: '1'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/absence/reject:
    post:
      tags:
        - ABSENCE
      summary: REJECT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                submission_id: 2
                authorization_by: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/overtime:
    get:
      tags:
        - OVERTIME
      summary: LIST
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '30'
        - name: user_id
          in: query
          schema:
            type: integer
          example: '3'
        - name: order
          in: query
          schema:
            type: string
          example: overtime_at:desc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/overtime/{id}:
    get:
      tags:
        - OVERTIME
      summary: DETAIL
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '52'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/overtime/submission/{overtime}:
    get:
      tags:
        - OVERTIME
      summary: LIST SUBMISSION
      security:
        - bearerAuth: []
      parameters:
        - name: overtime
          in: path
          schema:
            type: integer
          required: true
          example: '57'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/overtime/list/submission:
    get:
      tags:
        - OVERTIME
      summary: LIST SUBMISSION - ADMIN
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: start_date
          in: query
          schema:
            type: string
          example: '2023-05-31 00:00:00'
        - name: end_date
          in: query
          schema:
            type: string
          example: '2023-05-31 23:59:00'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/overtime/submission:
    post:
      tags:
        - OVERTIME
      summary: SUBMISSION
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 4
                overtime_at: '2023-04-28'
                desc: Kerjaan harus dilanjut
                attachment: ''
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/overtime/cancel:
    post:
      tags:
        - OVERTIME
      summary: CANCEL
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                overtime_id: '54'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/overtime/approve:
    post:
      tags:
        - OVERTIME
      summary: APPROVE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                submission_id: 18
                authorization_by: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/overtime/reject:
    post:
      tags:
        - OVERTIME
      summary: REJECT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                submission_id: 12
                authorization_by: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/presence:
    get:
      tags:
        - PRESENCE
      summary: LIST
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: user_id
          in: query
          schema:
            type: integer
          example: '3'
        - name: limit
          in: query
          schema:
            type: integer
          example: '30'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/presence/{id}:
    get:
      tags:
        - PRESENCE
      summary: DETAIL
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '5'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/presence/check_in:
    post:
      tags:
        - PRESENCE
      summary: CHECK IN
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 4
                check_in: '2023-04-26 8:00:00'
                position_check_in:
                  lat: '0'
                  lng: '0'
                type: wfh
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/presence/check_out:
    post:
      tags:
        - PRESENCE
      summary: CHECK OUT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 4
                check_out: '2023-04-19 17:00:00'
                position_check_out:
                  lat: '0'
                  lng: '0'
                description: Pekerjaan selesai
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/presence/start_overtime:
    post:
      tags:
        - PRESENCE
      summary: START OVERTIME
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 3
                overtime_start_at: '2023-03-20 19:00:00'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/presence/end_overtime:
    post:
      tags:
        - PRESENCE
      summary: END OVERTIME
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 3
                overtime_end_at: '2023-03-20 22:00:00'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/presence/start_holiday_overtime:
    post:
      tags:
        - PRESENCE
      summary: START HOLIDAY OVERTIME
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 3
                overtime_start_at: '2023-03-11 7:00:00'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/presence/end_holiday_overtime:
    post:
      tags:
        - PRESENCE
      summary: END HOLIDAY OVERTIME
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 3
                overtime_end_at: '2023-03-11 13:00:00'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/report:
    get:
      tags:
        - REPORT
      summary: LIST
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/report/create:
    post:
      tags:
        - REPORT
      summary: CREATE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Report Juni
                month_report: '6'
                year_report: '2023'
                generated_by: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/report/generate/{id}:
    post:
      tags:
        - REPORT
      summary: GENERATE
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ''
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/report/download_excel/{id}:
    get:
      tags:
        - REPORT
      summary: DOWNLOAD EXCEL
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/report/rekap_karyawan:
    post:
      tags:
        - REPORT
      summary: REKAP KARYAWAN
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 3
                month: '06'
                year: '2023'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/report/rekap_detail_karyawan:
    post:
      tags:
        - REPORT
      summary: REKAP DETAIL KARYAWAN
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 4
                month: '03'
                year: '2023'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
